export type ActionType = string;

export const START_LOGIN: ActionType = 'START_LOGIN'
export const END_LOGIN: ActionType = 'END_LOGIN'

export const START_VERIFY_AUTH: ActionType = 'START_VERIFY_AUTH'
export const END_VERIFY_AUTH: ActionType = 'END_VERIFY_AUTH'

export const START_ES_SEARCH: ActionType = 'START_ES_SEARCH'
export const END_ES_SEARCH: ActionType = 'END_ES_SEARCH'

export const GET_ES_START: ActionType = 'GET_ES_START'
export const GET_ES_END: ActionType = 'GET_ES_END'

export const START_CARRIER_SEARCH: ActionType = 'START_CARRIER_SEARCH'
export const END_CARRIER_SEARCH: ActionType = 'END_CARRIER_SEARCH'
export const GET_CARRIER_START: ActionType = 'GET_CARRIER_START'
export const GET_CARRIER_END: ActionType = 'GET_CARRIER_END'

export const GET_CARRIER_MONITORING_SITES_START: ActionType = 'GET_CARRIER_MONITORING_SITES_START'
export const GET_CARRIER_MONITORING_SITES_END: ActionType = 'GET_CARRIER_MONITORING_SITES_END'

export const GET_OWNER_BEGIN: ActionType = 'GET_OWNER_BEGIN'
export const GET_OWNER_END: ActionType = 'GET_OWNER_END'

export const GET_SATELLITES: ActionType = 'GET_SATELLITES'
export const GET_SATELLITES_END: ActionType = 'GET_SATELLITES_END'

export const CHANGE_PAGE: ActionType = 'CHANGE_PAGE'

export const GET_DASHBOARD_START: ActionType = 'GET_DASHBOARD_START'
export const GET_DASHBOARD_END: ActionType = 'GET_DASHBOARD_END'

export const ADD_ERROR_MESSAGE = 'ADD_ERROR_MESSAGE'
export const DISMISS_ERROR_MESSAGE = 'DISMISS_ERROR_MESSAGE'

export const CHANGE_ES_GRID_FILTERS = 'CHANGE_ES_GRID_FILTERS'
export const CHANGE_ES_GRID_GROUPING = 'CHANGE_ES_GRID_GROUPING'

export const CHANGE_CARRIER_GRID_FILTERS = 'CHANGE_CARRIER_GRID_FILTERS'
export const CHANGE_CARRIER_GRID_GROUPING = 'CHANGE_CARRIER_GRID_GROUPING'

export const ENSURE_HEIGHT_FULL = 'ENSURE_HEIGHT_FULL'
export const ENSURE_HEIGHT_AUTO = 'ENSURE_HEIGHT_AUTO'

export const GET_CARRIER_CHANGE_LOGS_START = 'GET_CARRIER_CHANGE_LOGS_START'
export const GET_CARRIER_CHANGE_LOGS_END = 'GET_CARRIER_CHANGE_LOGS_END'

export const GET_CARRIER_OPERATOR_NOTES_START = 'GET_CARRIER_OPERATOR_NOTES_START'
export const GET_CARRIER_OPERATOR_NOTES_END = 'GET_CARRIER_OPERATOR_NOTES_END'

export const ADD_CARRIER_CHANGE_LOG = 'ADD_CARRIER_CHANGE_LOG'
export const ADD_CARRIER_CHANGE_LOG_END = 'ADD_CARRIER_CHANGE_LOG_END'

export const GET_OPERATORS = 'GET_OPERATORS'
export const GET_OPERATORS_END = 'GET_OPERATORS_END'

export const GET_CARRIER_CONSTANTS = 'GET_CARRIER_CONSTANTS'
export const GET_CARRIER_CONSTANTS_END = 'GET_CARRIER_CONSTANTS_END'

export const GET_CARRIER_ES_SITES = 'GET_CARRIER_ES_SITES'
export const GET_CARRIER_ES_SITES_END = 'GET_CARRIER_ES_SITES_END'

export const SAVE_CARRIER_LINEUP_OP_NOTES = 'SAVE_CARRIER_LINEUP_OP_NOTES'
export const SAVE_CARRIER_LINEUP_OP_NOTES_END = 'SAVE_CARRIER_LINEUP_OP_NOTES_END'

export const SAVE_CARRIER_TEARDOWN_OP_NOTES = 'SAVE_CARRIER_TEARDOWN_OP_NOTES'
export const SAVE_CARRIER_TEARDOWN_OP_NOTES_END = 'SAVE_CARRIER_TEARDOWN_OP_NOTES_END'

export const TEMP_UPDATE_CAPACITY_SEARCH = 'TEMP_UPDATE_CAPACITY_SEARCH'
export const CANCEL_TEMP_UPDATE_CAPACITY_SEARCH = 'CANCEL_TEMP_UPDATE_CAPACITY_SEARCH'

export const UPDATE_CAPACITY_SEARCH = 'UPDATE_CAPACITY_SEARCH'
export const RESET_CAPACITY_SEARCH = 'RESET_CAPACITY_SEARCH'
export const ADD_MANUAL_FILTER = 'ADD_MANUAL_FILTER'

export const CAPACITY_SEARCH_START = 'CAPACITY_SEARCH_START'
export const CAPACITY_SEARCH_END = 'CAPACITY_SEARCH_END'

export const GET_COUNTRIES = 'GET_COUNTRIES'
export const GET_COUNTRIES_END = 'GET_COUNTRIES_END'

export const GET_CITY = 'GET_CITY'
export const GET_CITY_END = 'GET_CITY_END'

export const GET_BEAM = 'GET_BEAM'
export const GET_BEAM_END = 'GET_BEAM_END'


export enum LoadingTypes {
    UNREQUESTED = 0,
    LOADING = 1,
    LOADED = 2
}
